version: '3.8'
services:
  #Reverse Proxy with NGINX
  nginx:
    image: nginx:1.25-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
        - '${APP_PORT:-80}:80'
    volumes:
        - ./:/var/www
        - ./docker/nginx:/etc/nginx/conf.d
    networks:
        - frameworknet
  #PHP Service
  php:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: php
    environment:
      - APP_ENV=${APP_ENV}
      - USER=${APP_USER:-dev}
      - PORT=9000
    working_dir: /var/www
    restart: unless-stopped
    volumes:
      - .:/var/www
      - ./docker/php.ini:/usr/local/etc/php/conf.d/custom-php.ini
    networks:
      - frameworknet
  #Database Service
  database:
    image: mysql
    restart: always
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
    ports:
      - "${FORWARD_DB_PORT:-3306}:3306"
    volumes:
      - ./.db/:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
      retries: 3
      timeout: 5s
    networks:
      - frameworknet
networks:
  frameworknet:
    driver: bridge
